graylog-main:
    restart: always
    environment:
        GRAYLOG_USERNAME: "${graylog_username}"
        GRAYLOG_PASSWORD: "${graylog_password}"
        GRAYLOG_RETENTION: "${graylog_retention}"
        GRAYLOG_NODE_ID: "${graylog_node_id}"
        GRAYLOG_SERVER_SECRET: "${graylog_secret}"
    image: "graylog2/allinone"
    labels:
        io.rancher.container.hostname_override: container_name
    ports:
        - "9000:9000"
        - "12201:12201"
        - "12201:12201/udp"
    volumes:
        - /graylog/data:/var/opt/graylog/data
        - /graylog/logs:/var/log/graylog
