graylog-main:
    restart: always
    environment:
        GRAYLOG_USERNAME: "admin"
        GRAYLOG_PASSWORD: ""
        GRAYLOG_RETENTION: ""
        GRAYLOG_NODE_ID: "graylog"
        GRAYLOG_MASTER: ""
    image: "graylog2/server:2.0.0-rc.1-1"
    labels:
        io.rancher.container.hostname_override: container_name
    external_links:
        - ${mongo_service}:mongo
        - ${es_service}:elasticsearch
    ports:
        - "9000:9000"
        - "12900:12900"
