.catalog:
    name: "Graylog"
    version: "v1.3.4"
    description: "Open source log management that actually works."
    questions:
        - variable: graylog_es
          description: "ElasticSearch Service Graylog Cluster"
          label: "ElasticSearch Service"
          type: "service"
          required: true
        - variable: graylog_password
          description: "Password in sha2"
          label: "SHA2 Password"
          type: "string"
          required: true
        - variable: graylog_secret
          description: "Password secret"
          label: "Password secret"
          type: "string"
          required: true
