.catalog:
    name: "Graylog"
    version: "v1.3.4"
    description: "Open source log management that actually works."
    uuid: "graylog-0"
    questions:
        - variable: mongo_service
          description: "Service MongoDB lié"
          label: "Service MongoDB"
          type: "service"
          required: true
        - variable: es_service
          description: "Service ElasticSearch lié"
          label: "Service ElasticSearch"
          type: "service"
          required: true
        - variable: graylog_master
          description: "Serveur Graylog maître (dans le cas d'un cluster)"
          label: "Serveur Graylog maître"
          type: "string"
        - variable: graylog_node_id
          description: "Set server node ID"
          label: "Node ID"
          type: "string"
          default: "graylog"
          required: true
        - variable: graylog_retention
          description: "Configure how long or how many logs should be stored"
          label: "Retention"
          type: "string"
        - variable: "graylog_username"
          description: "Set username for admin user"
          label: "Username"
          type: "string"
          default: "admin"
          required : true
        - variable: "graylog_password"
          description: "Set admin password"
          label: "Password"
          type: "string"
