version: '2'
catalog:
  name: E2LBK
  version: v5.5.0
  description: Logging and monitoring your stack
  questions:
    - variable: "VOLUME_DRIVER"
        type: "string"
        label: "Volume driver for data"
        description: |
          Specifiy docker volume driver to use
        default: "rancher-nfs"
        required: true
    - variable: "METRICBEAT"
        label: "Activate metricbeat"
        default: true
        required: true
        type: enum
        options:
          - false
          - true
    - variable: "PACKETBEAT"
        label: "Activate packetbeat"
        default: false
        required: true
        type: enum
        options:
          - false
          - true
services:
  logstash-config:
    metadata:
      logstash: &id001
        inputs: |+
          udp {
            port => 5000
            codec => "json"
          }

        outputs: |+
          elasticsearch {
            hosts => ["elasticsearch:9200"]
          }
          stdout {
            codec => rubydebug
          }
    scale: 1
  logstash:
    metadata:
      logstash: *id001
    scale: 1