cassandra-datavolume:
  net: none
  labels:
      io.rancher.container.hostname_override: container_name
      io.rancher.container.start_once: true
  volumes:
      - /var/lib/cassandra
  entrypoint: /bin/true
  image: busybox
cassandra:
  image: cassandra:3.7
  labels:
    io.rancher.container.hostname_override: container_name
    io.rancher.sidekicks: cassandra-datavolume
  tty: true
  volumes_from:
      - cassandra-datavolume
kong:
  image: littlebaydigital/kong:0.8.3
  ports:
  - 7946:7946/tcp
  - 7946:7946/udp
  - 8000:8000/tcp
  - 8001:8001/tcp
  - 8443:8443/tcp
  environment:
    CLUSTER_LISTEN: rancher
    DATABASE: cassandra:9046
    CASSANDRA_CONTACT_POINTS: cassandra
    CASSANDRA_KEYSPACE: kong
    CASSANDRA_USER: cassandra
    CASSANDRA_PASSWORD: cassandra
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
    io.rancher.container.hostname_override: container_name
  tty: true
  links:
    - cassandra:cassandra
kong-dashboard:
  image: pgbi/kong-dashboard
  ports:
    - 8080:8080/tcp
  labels:
    io.rancher.scheduler.global: 'true'
    io.rancher.container.pull_image: always
  tty: true
