version: '2'
services:
    logentries-agent:
        image: logentries/docker-logentries:0.2.1
        restart: always
        stdin_open: true
        tty: true
        privileged: true
        volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/etc/hostname:/etc/hostname:ro'
        labels:
          io.rancher.scheduler.global: 'true'
          io.rancher.container.hostname_override: container_name
        command: ${logentries_command}
    logspout:
        image: gliderlabs/logspout:v3.2.3
        restart: always
        stdin_open: true
        tty: true
        privileged: true
        volumes:
        - '/var/run/docker.sock:/var/run/docker.sock'
        - '/etc/hostname:/etc/hostname:ro'
        labels:
          io.rancher.scheduler.global: 'true'
          io.rancher.container.hostname_override: container_name
        command: ${logspout_address}
