name: "LogEntries agent"
description: |
  Real-time performance tracking and visualization of your container-based application deployment
version: "v0.2.1"
category: Monitoring
license: The MIT License
